// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLU_WRWzQG41aZ6buiJ7JLmD_9M7TRoBA',
    appId: '1:259399537871:web:c64869e93532ef181ed3ba',
    messagingSenderId: '259399537871',
    projectId: 'music-app-6316b',
    authDomain: 'music-app-6316b.firebaseapp.com',
    storageBucket: 'music-app-6316b.appspot.com',
    measurementId: 'G-4FKK2P2QT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR74cr9r-Tng_-1G5xn7Gaxor-WgPtrWQ',
    appId: '1:259399537871:android:4400457711968f221ed3ba',
    messagingSenderId: '259399537871',
    projectId: 'music-app-6316b',
    storageBucket: 'music-app-6316b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbMdyFIpvYoV6MqUMitb0sbPoMk3Ib9HM',
    appId: '1:259399537871:ios:a3475992880fa7341ed3ba',
    messagingSenderId: '259399537871',
    projectId: 'music-app-6316b',
    storageBucket: 'music-app-6316b.appspot.com',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbMdyFIpvYoV6MqUMitb0sbPoMk3Ib9HM',
    appId: '1:259399537871:ios:a3475992880fa7341ed3ba',
    messagingSenderId: '259399537871',
    projectId: 'music-app-6316b',
    storageBucket: 'music-app-6316b.appspot.com',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLU_WRWzQG41aZ6buiJ7JLmD_9M7TRoBA',
    appId: '1:259399537871:web:4d90b9f09e2893301ed3ba',
    messagingSenderId: '259399537871',
    projectId: 'music-app-6316b',
    authDomain: 'music-app-6316b.firebaseapp.com',
    storageBucket: 'music-app-6316b.appspot.com',
    measurementId: 'G-MQH28CBLJC',
  );
}
